### ISSUE TITLE
what IDE can I use to import the project?

### ISSUE THREAD

**Issue by chakpongchung** [dnikolovv/haskell-tic-tac-toe#2]
Very interesting work!

**Comment by dnikolovv** [comment]
Thank you! Well, there isn't really a Haskell IDE. Perhaps the closest you can get is [intellij-haskell](https://github.com/rikvdkleij/intellij-haskell).

**Comment by chakpongchung** [comment]
then what is your development environment? say how do you do linting, formatting, code navigation like jump to definition and all that?

**Comment by dnikolovv** [comment]
I use intellij-haskell (it comes with hlint for linting and stylish-haskell for formatting). But it only works for `stack` projects. A colleague of mine uses Visual Studio Code + hie and is happy with that.

Sadly, intellij-haskell often hangs/stops working for no reason. The only reason I'm still using it is because it gives you "go to definition" for external library code, meaning you can browse your dependencies' source.

Fortunately, GHC will soon have [hie files](https://www.haskell.org/ghc/blog/20190626-HIEFiles.html), which will make this "go to external definition" possible for other editors. I'll probably switch to vs code/emacs then.

**Comment by chakpongchung** [comment]
I am now using VS code with hie to look into your code. Sadly, jump-to-definition is not working.

**Comment by dnikolovv** [comment]
Great! Well, hopefully after hie files jump-to-definition will be better across editors.
